version: "3.7"
services:
  appsec:
    restart: "no"
    build: .
    ports:
      - 8080:5000
    secrets:
      - SECRET_KEY
      - master_password
      - master_phone
    deploy:
      mode: replicated
      replicas: 4
secrets:
  SECRET_KEY:
    file: ./SECRET_KEY.txt
  master_password:
    file: ./master_password.txt
  master_phone:
    file: ./master_phone.txt